# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b997438615d5f0068037c566bd815089cf8d209ac0b3a8907443ea6f0cd707e2f41e8f832fe212ace372cc9500c41eb656994c63575aed1a16cb5254d8f83bc0

test:
  secret_key_base: 3c7d0e773a24b2812d32c7a261718b6d22f8469f207cd8d71f7ae928eb26e8077a680b5292a643946b2cd3abce51d1d7230af71b6838328d8d1ca6412076e5a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
